### PR TITLE
accept more types of file: URI

### LINKED ISSUE #279: heuristic_parse breaks 'file:' URIs with UNC paths
File URIs can have 0, 1, 2, 3, 4, or sometimes 5 slashes after the `"file:"` part. `heuristic_parse` assumes always 0 or 3.

### PR DESCRIPTION
**Pull request by phluid61**
* "file:////share/path/file" => UNC/SMB share
* "file://localhost/path"    => "file:///path"
* "file://foo/bar"           => typo, becomes "file:///foo/bar"

Includes additional rspec tests.

Fixes #279

### CODE REVIEW

**Comment by phluid61** [comment]
I can easily change it to use `//` literals and/or remove the `i` modifiers and/or use `gsub!` if that makes it more acceptable.

**Comment by sporkmonger** [comment]
If anything, I'd rather convert everything to match `%r` style. It's the right approach here.

**Comment by olleolleolle** [comment]
@sporkmonger Oh, if you didn’t see that - this PR now uses your recommendation of delimiters for regex.

**Comment by sporkmonger** [comment]
So we recently actually got a real spec for `file:` URIs instead of a de facto standard established by common practice. I haven't had a chance to dive into it yet, but I'm inclined to wait on this PR until myself or another maintainer has had a chance to read it through.

https://tools.ietf.org/html/rfc8089

**Comment by phluid61** [comment]
(Guess who authored RFC 8089...)

**Comment by sporkmonger** [comment]
Bahahaha, nice. Totally missed that, LOL.

**Comment by sporkmonger** [comment]
Gave it a second quick review, and I'm happy w/ where this is at, and I'll trust that you did the right things where the spec is concerned. 😁

**Pull request merged**
