### PR TITLE
Freeze string literals

### PR DESCRIPTION
**Pull request by PeterGillis**
Hi there Sporkmonger,

My Pull-request deletes the `.freeze` from the gemspec file and instead adds to the top of the file the magic comment:

`# frozen_string_literal: true`

This should solve the freeze issue and makes the file a little cleaner.

I hope that helps.

### CODE REVIEW

**Comment by dentarg** [comment]
> This should solve the freeze issue

What issue is that?

FYI, the gemspec is generated by rake, see the Rakefile and [its task](https://github.com/sporkmonger/addressable/tree/master/tasks)

**Comment by PeterGillis** [comment]
Hi there, 
Sorry for not being clear, let me clarify. 
When I found the gem (it is a dependency of another gem I am using) I noticed that there was a large amount of `.freeze' statements.
I should not have said 'freeze issue' I just meant that maybe using `# frozen_string_literal: true` could avoid using `.freeze` so much. A small suggestion, not a solution to a problem.

**Comment by dentarg** [comment]
@PeterGillis I see, are you able to provide steps to reproduce that problem?

Then we can try to understand if it is possible to fix in addressable

**Comment by PeterGillis** [comment]
@dentarg, there's no problem, sorry I think you misunderstood. 
My PR is a proposal to re-factor, to make the code more DRY. 
Substituting writing `.freeze` multiple times and instead writing it in the magic comment once only.
Magic comment meaning this:
`# frozen_string_literal: true` . 
See [this:](https://stackoverflow.com/questions/37799296/what-does-the-comment-frozen-string-literal-true-do)
There's no 'problem' here to reproduce.

**Comment by dentarg** [comment]
@PeterGillis ah got it, I miss understood 

But you can't make this change here, as the gemspec is generated by code, see my first comment

**Pull request closed without merging**
