### PR TITLE
Work with ruby 2.3's --enable-frozen-string-literal

### PR DESCRIPTION
**Pull request by jeremyevans**
These changes are the minimal ones necessary to allow Sequel's specs
to pass. There may well be other changes that are required.

### CODE REVIEW

**Comment by sporkmonger** [comment]
Are there tests you can write that would fail without this change?

**Comment by jeremyevans** [comment]
Have you tried running the addressable specs with `ruby --enable-frozen-string-literal` using ruby 2.3?  I'm assuming they would fail if you didn't make this change.  They may fail for other reasons in addition to this change.  To be fair, I didn't do that.  However, from testing Sequel (using data_objects, which uses addressable), this appears to be an issue.

**Comment by sporkmonger** [comment]
No, I hadn't, I'll give it a go, see what happens.

**Comment by sporkmonger** [comment]
Can't get it past bundler actually. How did you even run Sequel's tests? I'm getting exceptions long before it hits the test runner.

**Comment by jeremyevans** [comment]
I've heard bundler's master branch (unreleased) contains fixes.  Personally, I don't use bundler for testing (or much at all), so it wasn't an issue for me.

If you just want to diagnose frozen string literal issues in your own code without worrying about other people's code, just add `# frozen-string-literal: true` to the top of all of the lib files, and don't run with `--enable-frozen-string-literal`.

**Comment by sporkmonger** [comment]
Yeah, I see the test failures now.

**Comment by sporkmonger** [comment]
I merged this because it seemed to have an improvement, however it definitely does not fix all failing tests.

**Comment by sporkmonger** [comment]
I see 498 test failures still with frozen string literals.

**Pull request merged**
