### PR TITLE
Add URI.abolute_uri? to test if input is absolute?

### PR DESCRIPTION
**Pull request by ashmaroli**
To reduce memory-allocations and therefore speed  up the operation.

### CODE REVIEW

**Comment by ashmaroli** [comment]
@dentarg Any feedback on this..?

**Comment by sporkmonger** [comment]
To be honest I'm not fully convinced. I'm all for performance optimization where it makes sense, but I'm pretty reluctant to change the API surface just to get a performance boost in a specific scenario.

**Comment by ashmaroli** [comment]
We introduced a cache (and memoizations at some places) around the code employing `Addressable`.

So while I still feel it would be *better* for testing whether given `uri` is absolute or not by just checking if the `uri` has a valid `scheme` pattern`, instead of parsing it (which is what creates numerous intermediate objects) into an `Addressable::URI` object and then checking its attribute, this may no longer be needed for our use-cases.

**Pull request closed without merging**
