### PR TITLE
Test against TruffleRuby

### PR DESCRIPTION
**Pull request by rafaelfranca**
Test against the TruffleRuby implementation.

All tests are green already.

### CODE REVIEW

**Comment by dentarg** [comment]
Sure, doesn't hurt I think... do you know why TruffleRuby is so slow?

**Comment by rafaelfranca** [comment]
I'll still investigate why running the tests takes 2 minutes compared with the 19s of jruby, but part of why the build is slow are the 200s on bundle install that is fixed by the cache.

**Comment by dentarg** [comment]
> 200s on bundle install

Looks like a known issue: https://github.com/oracle/truffleruby/issues/1398

**Comment by dentarg** [comment]
And it looks like others have the same experience running their tests: https://github.com/oracle/truffleruby/issues/1415 (I added the difference for addressable there)

**Pull request merged**
