### PR TITLE
Remove redundant colon in Addressable::URI::CharacterClasses::AUTHORITY

### PR DESCRIPTION
**Pull request by ukolovda**
Addressed to #437

### CODE REVIEW

**Comment by masterofmasters13** [comment]
debug all ci or authority

**Comment by ukolovda** [comment]
Bug found in used `idn-ruby` gem, see https://github.com/deepfryed/idn-ruby/issues/9

**Comment by ukolovda** [comment]
@masterofmasters13  please approve workflow, now all tests should pass with latest `idn-ruby` 0.1.4.

**Comment by masterofmasters13** [comment]
can we please scan and eliminate all bugs im currently very busy and still
learning the deveopment ins and outs

**Comment by dentarg** [comment]
@ukolovda I approved the CI, I don't know who @masterofmasters13 is, the account joined GitHub just two days ago

**Comment by ukolovda** [comment]
> @ukolovda I approved the CI, I don't know who @masterofmasters13 is, the account joined GitHub just two days ago

Ohh... Sorry. 
And thank you!

CI is green now.

**Review by dentarg — APPROVED** [review]
Looks OK to me!

I can only see `Addressable::URI::CharacterClasses::AUTHORITY` being used at

https://github.com/sporkmonger/addressable/blob/901e563386c8a0387bd03f908e320b1c171eb59a/lib/addressable/uri.rb#L628-L629

In `encode_component` it is then always used in this way:


https://github.com/sporkmonger/addressable/blob/901e563386c8a0387bd03f908e320b1c171eb59a/lib/addressable/uri.rb#L389 https://github.com/sporkmonger/addressable/blob/901e563386c8a0387bd03f908e320b1c171eb59a/lib/addressable/uri.rb#L411-L413

which triggers the warning:

```ruby
$ irb -w -r addressable/uri
irb(main):001:0> Addressable::VERSION::STRING
=> "2.8.0"
irb(main):002:0> Regexp.compile("[#{Addressable::URI::CharacterClasses::AUTHORITY}]")
(irb):2: warning: character class has duplicated range: /[a-zA-Z0-9\-\.\_\~\!\$\&\'\(\)\*\+\,\;\=\:\@\[\:\]]/
=> /[a-zA-Z0-9\-\.\_\~\!\$\&\'\(\)\*\+\,\;\=\:\@\[\:\]]/
````

**Pull request merged**
