### PR TITLE
various: fix miscellaneous typos

### PR DESCRIPTION
**Pull request by p-linnane**
This PR aims to fix various minor typos across the codebase. I noticed some of these when doing the same review on our Homebrew/brew repo, since we use addressable.

### CODE REVIEW

**Review by dentarg — APPROVED** [review]

**Comment by p-linnane** [comment]
@dentarg any chance you'd be able to cut a patch release? We aren't able to see this downstream without one. Thanks!

**Comment by dentarg** [comment]
Patch release for doc fixes? Hehe, that's a first for me

What project is downstream? Curious

**Comment by p-linnane** [comment]
I'm a maintainer for Homebrew (https://github.com/Homebrew/brew). I'm working on remedying typos in our codebase, and since we use addressable, the typos I fixed in this PR are showing up in my results.

**Comment by p-linnane** [comment]
It's not a big deal if you don't want to cut a patch release for this. I can wait til the next actual release, I just figured I'd ask 😄.

**Comment by dentarg** [comment]
No release planned right now, no actual code changes has happen since last release :)

I do want to automate the release process a bit so cutting one just for the sake of it may happen. No promises though.

**Comment by p-linnane** [comment]
Sounds good. Thank you! 🙇

**Pull request merged**
