### PR TITLE
Test against 2.1 & 2.2

### PR DESCRIPTION
**Pull request by sanemat**
- Test against ruby 2.2
- Remove patch version after ruby 2.1 on travis-ci

### CODE REVIEW

**Comment by sporkmonger** [comment]
Out of curiosity, why are you dropping the patch version numbers here?

**Comment by sanemat** [comment]
@sporkmonger 
Ruby uses semver after 2.1.0.

```yaml
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1
- 2.2
```

So this means 1.9.2-p330(latest), 1.9.3-p551(latest), 2.0.0-p643(latest), 2.1.5(latest), 2.2.1(latest).
But 2.1.0 means exactly 2.1.0.

* https://www.ruby-lang.org/en/news/2013/12/21/ruby-version-policy-changes-with-2-1-0/
* https://github.com/sstephenson/ruby-build/tree/a55247a8c5eacc485ed1ce8bc0129376d6b00298/share/ruby-build

**Comment by sporkmonger** [comment]
TIL.

**Comment by sanemat** [comment]
thanks! :smiley:

**Pull request merged**
