### PR TITLE
Avoid producing invalid urls for partial form-style query expansion

### PR DESCRIPTION
**Pull request by pezra**
When `http://example.com/{?a,b}` is partially expanded with `b: 2` the result must be `http://example.com/?b=2{&a}`. That way if the final expansion is done w/ `a` undefined the resulting URL will be valid.

If the form-style query vars are not reordered and final expansion is done w/ `a` undefined the result is
`http://example.com/&b=2` which is clearly malformed.

### CODE REVIEW

**Comment by pezra** [comment]
This addresses issue #200.

**Comment by sporkmonger** [comment]
Thanks for this PR, sorry it took me _so_ long to get to it.

**Comment by faucct** [comment]
Is still an issue when expanding `b` to `nil`:

```ruby
require 'addressable'

puts Addressable::Template.new(<<~URI.chomp).partial_expand(b: nil).pattern
  http://example.com{?a,b}
URI
# => http://example.com{&a}
```

**Comment by dentarg** [comment]
@faucct I think you should open a new issue, if you want the problem to be addressed

**Pull request merged**
