### PR TITLE
Fixed `Addressable::URI#inspect` to use `self.class`.

### PR DESCRIPTION
**Pull request by postmodern**
This will allow sub-classing `Addressable::URI` and have the sub-classes name show up in the `inspect` output.

```ruby
class CustomURL < Addressable::URI

  def custom_method
     ...
  end

end

uri = CustomURL.parse("https://example.com")
# => #<CustomURL:0x1824 URI:https://example.com>
```

### CODE REVIEW

**Review by dentarg — APPROVED** [review]
LGTM

```ruby
# main
$ ruby -raddressable/uri -e 'class CustomURIClass < Addressable::URI;end; p CustomURIClass.new.inspect'
"#<Addressable::URI:0x3c URI:>"

# this PR
$ ruby -Ilib -raddressable/uri -e 'class CustomURIClass < Addressable::URI;end; p CustomURIClass.new.inspect'
"#<CustomURIClass:0x3c URI:>"
```

**Comment by dentarg** [comment]
Unfortunately merging is blocked by https://github.com/sporkmonger/addressable/pull/543 – I can not resolve this myself

**Comment by postmodern** [comment]
Hmm, GitHub Actions suddenly sprung to life and ran on my work of `addressable-uri`. Only one job failed (macOS tests) with no output.
https://github.com/postmodern/addressable/actions/runs/10360606576/job/28679370905

**Comment by sporkmonger** [comment]
Should be unblocked now! Sorry I didn't see the problem earlier!

**Pull request merged**
