### PR TITLE
Allow use of `public_suffix` 5, update gemspec task

### PR DESCRIPTION
**Pull request by dentarg**
Follow-up to #460

### CODE REVIEW

**Comment by dentarg** [comment]
@sporkmonger can you cut a new release with this change? I think people wants it

(FYI @petergoldstein I can not make releases)

**Comment by petergoldstein** [comment]
@sporkmonger Any chance we can get a published gem with this change?

**Comment by dentarg** [comment]
I should be able to cut releases now, I will try to do it next week

**Comment by petergoldstein** [comment]
Thanks @dentarg .  I'll watch for that.

**Comment by dentarg** [comment]
@petergoldstein 2.8.1 should be out now

**Comment by petergoldstein** [comment]
Thanks @dentarg .  Appreciate it.

**Pull request merged**
